### ISSUE TITLE
Pente Fino - Single/Ficha da Prática

### ISSUE THREAD

**Issue by diogosp** [brasadesign/osc#1]
@willowmagrini percebi que há um pente fino pra fazer na ficha. A coluna da esquerda com os dados básicos do projeto está encavalando com a descrição na direita:

<img width="1165" alt="rede_brasileira_de_grupos_de_consumo_responsavel_ _observatorio_da_sociedade_civil" src="https://cloud.githubusercontent.com/assets/5107285/24365794/7b67fa16-12ed-11e7-8222-3c672c910a66.png">

isto acontece em todas as fichas

**Comment by willowmagrini** [comment]
Fixed with https://github.com/brasadesign/osc/commit/7b239c7932cba43f13120233714bfc9b043a0ac2
